import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import HeroBanner from "../components/Herobanner";
import AboutS from "../components/AboutS";
import Services from "../components/Services";
import Stats from "../components/Stats";
import Blogsection from "../components/Blogsection";

import { createClient } from "contentful";
export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  });

  const res = await client.getEntries({ content_type: "post" });

  return {
    props: {
      posts: res.items,
      revalidate: 10,
    },
  };
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div>
      <Head>
        <title>Crest Valuations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <HeroBanner />
      <AboutS />
      <Services />
      <Stats />
      <Blogsection posts={posts} />
    </div>
  );
}
